import React from 'react';
import { FinalReportData } from '../../server/services/pipelineService';
import { FinalReportHeader } from './final-report/FinalReportHeader';
import { CertificateVerificationBanner } from './final-report/CertificateVerificationBanner';
import { FourTruthsAuditTable } from './final-report/FourTruthsAuditTable';
import { CSICategoriesTable } from './final-report/CSICategoriesTable';
import { VerifiedInvoicesTable } from './final-report/VerifiedInvoicesTable';
import { PipelineTraceAuditList } from './final-report/PipelineTraceAuditList';

interface FinalReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  reportData: FinalReportData | null;
}

export function FinalReportModal({
  isOpen,
  onClose,
  reportData,
}: FinalReportModalProps) {
  if (!isOpen || !reportData) return null;

  const handlePrint = () => {
    window.print();
  };

  const handleExportJSON = () => {
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(reportData, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `${reportData.reportId}_Audit_Report.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  return (
    <div className="fixed inset-0 bg-black/70 backdrop-blur-xs z-50 flex items-center justify-center p-4 animate-in fade-in duration-200">
      <div className="bg-white rounded-2xl border border-slate-200 shadow-2xl max-w-4xl w-full max-h-[92vh] overflow-y-auto flex flex-col text-slate-900">
        <FinalReportHeader
          reportData={reportData}
          onExportJSON={handleExportJSON}
          onPrint={handlePrint}
          onClose={onClose}
        />

        <div className="p-8 space-y-6 text-xs text-slate-800 flex-1">
          <CertificateVerificationBanner reportData={reportData} />
          <FourTruthsAuditTable fourTruths={reportData.fourTruths} />
          <CSICategoriesTable csiCategories={reportData.csiCategories} />
          <VerifiedInvoicesTable verifiedInvoices={reportData.verifiedInvoices} />
          <PipelineTraceAuditList pipelineTrace={reportData.pipelineTrace} />

          {/* Certification Signoff */}
          <div className="pt-6 border-t border-slate-200 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 text-slate-500">
            <div>
              <p className="font-bold text-slate-900">Generated by GroundUp AI Engine</p>
              <p className="text-[11px]">Audit Timestamp: {new Date(reportData.generatedAt).toLocaleString()} · SHA256 Verified</p>
            </div>
            <div className="text-right">
              <p className="font-extrabold text-emerald-800 uppercase tracking-wider text-xs">COMPLIANCE CERTIFIED</p>
              <p className="text-[10px] text-slate-500">Zero Hallucination Guaranteed · Four Truths Reconciliation</p>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-200 bg-slate-50 flex items-center justify-between">
          <span className="text-xs text-slate-500">
            Certified document ready for Lender Draw submission & Sponsor reporting
          </span>
          <button
            onClick={onClose}
            className="px-4 py-2 bg-slate-900 text-white rounded-lg text-xs font-semibold hover:bg-black transition cursor-pointer"
          >
            Close Report
          </button>
        </div>
      </div>
    </div>
  );
}
