import { DemoPersona } from './types';

export const DIRECT_LOGIN_PERSONAS: DemoPersona[] = [
  {
    id: 'user-dev-1',
    name: 'Hardik Parikh',
    email: 'hardik@groundup.ai',
    company: 'GroundUp Development Partners',
    role: 'DEVELOPER_OWNER',
    roleTitle: 'Developer / Owner',
    roleBadge: 'Owner',
    badgeClass: 'bg-slate-900 text-white',
  },
  {
    id: 'user-cfo-1',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@groundup.ai',
    company: 'GroundUp Development Partners',
    role: 'CFO',
    roleTitle: 'CFO / Accounting',
    roleBadge: 'Finance',
    badgeClass: 'bg-emerald-100 text-emerald-800 border border-emerald-200',
  },
  {
    id: 'user-pm-1',
    name: 'Marcus Vance',
    email: 'marcus@vancepm.com',
    company: 'Vance PM Group',
    role: 'PM',
    roleTitle: 'Project Manager',
    roleBadge: 'Field & Schedule',
    badgeClass: 'bg-blue-100 text-blue-800 border border-blue-200',
  },
  {
    id: 'user-gc-fixed',
    name: 'Kunal Shah',
    email: 'kunal@shahbuilds.com',
    company: 'Kunal Shah Development',
    role: 'GC_FIXED',
    roleTitle: 'GC (Fixed / Milestone)',
    roleBadge: 'Milestones',
    badgeClass: 'bg-indigo-100 text-indigo-800 border border-indigo-200',
  },
  {
    id: 'user-gc-daily',
    name: 'Sylvia Concrete',
    email: 'sylvia@concretepros.com',
    company: 'Sylvia Concrete & Framing',
    role: 'GC_DAILY',
    roleTitle: 'GC (Daily Updates)',
    roleBadge: 'Daily Logs',
    badgeClass: 'bg-teal-100 text-teal-800 border border-teal-200',
  },
  {
    id: 'user-investor-1',
    name: 'Krutarth Shah',
    email: 'krutarth@apexcap.com',
    company: 'Apex Capital Partners',
    role: 'INVESTOR',
    roleTitle: 'Investor / Partner',
    roleBadge: 'Investor',
    badgeClass: 'bg-purple-100 text-purple-800 border border-purple-200',
  },
  {
    id: 'user-acct-1',
    name: 'Elena Rostova',
    email: 'elena@rostovacpa.com',
    company: 'Rostova CPA Group',
    role: 'ACCOUNTANT',
    roleTitle: 'Accountant / Controller',
    roleBadge: 'Ledger & AP',
    badgeClass: 'bg-cyan-100 text-cyan-800 border border-cyan-200',
  },
];
