import { DemoPersona } from './types';

export const DIRECT_LOGIN_PERSONAS: DemoPersona[] = [
  {
    id: 'user-owner-1',
    name: 'Hardik Parikh',
    email: 'hardik@groundup.ai',
    company: 'GroundUp Development Partners',
    role: 'OWNER',
    roleTitle: 'Developer / Owner',
    roleBadge: 'Owner',
    badgeClass: 'bg-slate-900 text-white',
  },
  {
    id: 'user-pm-1',
    name: 'Marcus Vance',
    email: 'marcus@vancepm.com',
    company: 'Vance PM Group',
    role: 'PROJECT_MANAGER',
    roleTitle: 'Project Manager',
    roleBadge: 'Field & Schedule',
    badgeClass: 'bg-blue-100 text-blue-800 border border-blue-200',
  },
  {
    id: 'user-gc-1',
    name: 'Kunal Shah',
    email: 'kunal@shahbuilds.com',
    company: 'Kunal Shah Development & Builders',
    role: 'GENERAL_CONTRACTOR',
    roleTitle: 'General Contractor',
    roleBadge: 'General Contractor',
    badgeClass: 'bg-teal-100 text-teal-800 border border-teal-200',
  },
  {
    id: 'user-fin-1',
    name: 'Sarah Jenkins',
    email: 'sarah.jenkins@groundup.ai',
    company: 'GroundUp Development Partners',
    role: 'FINANCE',
    roleTitle: 'Finance Director / CFO',
    roleBadge: 'Finance',
    badgeClass: 'bg-emerald-100 text-emerald-800 border border-emerald-200',
  },
  {
    id: 'user-acct-1',
    name: 'Elena Rostova',
    email: 'elena@rostovacpa.com',
    company: 'Rostova CPA Group',
    role: 'ACCOUNTANT',
    roleTitle: 'Project Accountant',
    roleBadge: 'Ledger & Audit',
    badgeClass: 'bg-cyan-100 text-cyan-800 border border-cyan-200',
  },
  {
    id: 'user-investor-1',
    name: 'Krutarth Shah',
    email: 'krutarth@apexcap.com',
    company: 'Apex Capital Partners',
    role: 'INVESTOR',
    roleTitle: 'Equity Investor / Partner',
    roleBadge: 'Investor',
    badgeClass: 'bg-purple-100 text-purple-800 border border-purple-200',
  },
  {
    id: 'user-viewer-1',
    name: 'Morgan Blake',
    email: 'morgan@consulting.com',
    company: 'Urban Asset Advisory',
    role: 'VIEWER',
    roleTitle: 'Read-Only Viewer',
    roleBadge: 'Viewer',
    badgeClass: 'bg-slate-100 text-slate-700 border border-slate-200',
  },
];
