import {
  FileSpreadsheet,
  FileCheck,
  Clock,
  Landmark,
  FileText,
  ShieldCheck,
} from 'lucide-react';
import { IntakeDocument } from './types';

export const INITIAL_INTAKE_DOCUMENTS: IntakeDocument[] = [
  {
    id: 'doc-sov',
    title: '1. Budget Sheet & Schedule of Values (SOV)',
    category: 'BUDGET_SPREADSHEET',
    fileName: '73_Broadway_SOV_v2_Approved.xlsx',
    fileSize: '1.4 MB',
    uploadedAt: 'Sep 1, 2025',
    shaHash: '8f4a1c9e...42a0',
    status: 'EXTRACTED_VERIFIED',
    extractedSummary: '12 budget lines · $1,820,000 total baseline budget · 10% contingency ($82K)',
    icon: FileSpreadsheet,
  },
  {
    id: 'doc-gc',
    title: '2. Executed General Contractor Contract',
    category: 'GC_CONTRACT',
    fileName: 'KP_Construction_AIA_A102_Executed.pdf',
    fileSize: '3.8 MB',
    uploadedAt: 'Sep 5, 2025',
    shaHash: '7b2d9f1a...991c',
    status: 'EXTRACTED_VERIFIED',
    extractedSummary: 'Commercial Model: Daily Updates / Open-Book · 12% GC Markup · Net 15 Payment Terms',
    icon: FileCheck,
  },
  {
    id: 'doc-timeline',
    title: '3. Master Construction Timeline & Gantt',
    category: 'SCHEDULE_SPREADSHEET',
    fileName: '73_Broadway_CPM_Schedule_Target_Jun2026.mpp',
    fileSize: '820 KB',
    uploadedAt: 'Sep 10, 2025',
    shaHash: '3e1c8d4a...5502',
    status: 'EXTRACTED_VERIFIED',
    extractedSummary: '12 critical path milestones · Target Completion: Jun 15, 2026',
    icon: Clock,
  },
  {
    id: 'doc-loan',
    title: '4. Construction Loan Approval Agreement',
    category: 'LOAN_APPROVAL',
    fileName: 'BCB_Bank_Commitment_Letter_Signed.pdf',
    fileSize: '2.1 MB',
    uploadedAt: 'May 1, 2025',
    shaHash: '4f8b91a2...3011',
    status: 'EXTRACTED_VERIFIED',
    extractedSummary: '$1,200,000 Facility · 9.75% APR · 18 Month Term · $75,000 Interest Reserve',
    icon: Landmark,
  },
  {
    id: 'doc-hud',
    title: '5. HUD-1 Settlement & Closing Statement',
    category: 'HUD_STATEMENT',
    fileName: 'HUD1_Settlement_73_Broadway_Closed.pdf',
    fileSize: '1.9 MB',
    uploadedAt: 'Apr 28, 2025',
    shaHash: '9a3e2c1b...8820',
    status: 'EXTRACTED_VERIFIED',
    extractedSummary: 'Purchase Price: $1,000,000 · Seller Credits: $15,000 · Title & Legal: $18,400',
    icon: FileText,
  },
  {
    id: 'doc-land',
    title: '6. Land Acquisition & Title Deed Statement',
    category: 'LAND_ACQUISITION',
    fileName: 'Hudson_County_Recorded_Deed_GroundUp.pdf',
    fileSize: '2.4 MB',
    uploadedAt: 'Apr 30, 2025',
    shaHash: '1c4e7a2b...7733',
    status: 'EXTRACTED_VERIFIED',
    extractedSummary: 'Recorded Book 9842 / Page 114 · Clean Title · Free of Liens or Encumbrances',
    icon: ShieldCheck,
  },
  {
    id: 'doc-bank',
    title: '7. Primary Project Operating Bank Statement',
    category: 'BANK_STATEMENT',
    fileName: 'BCB_Statement_August_2026.pdf',
    fileSize: '950 KB',
    uploadedAt: 'Sep 15, 2026',
    shaHash: '6d2a8c1e...1194',
    status: 'EXTRACTED_VERIFIED',
    extractedSummary: 'Starting Balance: $148,200 · 12 disbursements matched to spend ledger',
    icon: Landmark,
  },
];
