import { ActiveNavScreen, GroundUpRole, UserRole } from './types';

const baseScreens: Record<GroundUpRole, ActiveNavScreen[]> = {
  OWNER: [
    'portfolio',
    'project-detail',
    'acquisition',
    'permits',
    'financing',
    'budget',
    'draws',
    'timeline',
    'documents',
    'disposition',
    'recon',
    'reports',
    'deal-lab',
    'alerts',
    'settings',
    'cfo-recon',
    'investor-portal',
    'gc-fixed-portal',
    'gc-daily-portal',
  ],
  FINANCE: [
    'portfolio',
    'project-detail',
    'acquisition',
    'financing',
    'budget',
    'draws',
    'timeline',
    'documents',
    'disposition',
    'recon',
    'reports',
    'alerts',
    'settings',
    'cfo-recon',
    'investor-portal',
  ],
  PROJECT_MANAGER: [
    'portfolio',
    'project-detail',
    'acquisition',
    'permits',
    'budget',
    'timeline',
    'documents',
    'alerts',
    'gc-daily-portal',
  ],
  ACCOUNTANT: [
    'project-detail',
    'budget',
    'draws',
    'documents',
    'recon',
    'reports',
    'cfo-recon',
  ],
  INVESTOR: [
    'project-detail',
    'investor-portal',
    'disposition',
    'documents',
    'reports',
  ],
  VIEWER: [
    'project-detail',
    'permits',
    'timeline',
    'documents',
    'reports',
  ],
};

const fullScreens: Record<string, ActiveNavScreen[]> = {
  ...baseScreens,
  GENERAL_CONTRACTOR: [
    'project-detail',
    'timeline',
    'budget',
    'documents',
    'alerts',
    'gc-fixed-portal',
    'gc-daily-portal',
  ],
  DEVELOPER_OWNER: baseScreens.OWNER,
  CFO: baseScreens.FINANCE,
  PM: baseScreens.PROJECT_MANAGER,
  GC_FIXED: ['gc-fixed-portal', 'timeline', 'project-detail'],
  GC_DAILY: ['gc-daily-portal', 'timeline', 'project-detail'],
};

export const ROLE_ALLOWED_SCREENS: Record<string, ActiveNavScreen[]> = fullScreens;

export const ROLE_DEFAULT_SCREEN: Record<string, ActiveNavScreen> = {
  OWNER: 'portfolio',
  PROJECT_MANAGER: 'timeline',
  GENERAL_CONTRACTOR: 'timeline',
  FINANCE: 'portfolio',
  ACCOUNTANT: 'budget',
  INVESTOR: 'project-detail',
  VIEWER: 'project-detail',
  DEVELOPER_OWNER: 'portfolio',
  CFO: 'portfolio',
  PM: 'timeline',
  GC_FIXED: 'timeline',
  GC_DAILY: 'timeline',
};
