import { GroundUpRole, Permission, UserRole } from './types';

const basePermissions: Record<GroundUpRole, Permission[]> = {
  OWNER: [
    'portfolio:view',
    'organization:manage',
    'project:create',
    'project:delete',
    'project:view_overview',
    'project:view_financials',
    'project:settings',
    'deal_lab:access',
    'deal_lab:save_project',
    'acquisition:view',
    'acquisition:edit',
    'permits:view',
    'permits:edit',
    'financing:view',
    'financing:edit',
    'budget:view',
    'budget:edit',
    'change_order:create',
    'change_order:approve',
    'contingency:view',
    'contingency:manage',
    'draw:view',
    'draw:create_packet',
    'draw:review_queue',
    'draw:approve_lines',
    'draw:disburse_wire',
    'milestone:view',
    'milestone:log_progress',
    'delay:attribute',
    'field_log:create',
    'milestone_claim:submit',
    'recon:view',
    'recon:edit',
    'accounting:recon_matrix',
    'waiver:audit_view',
    'waiver:audit_manage',
    'document:view',
    'document:upload',
    'amex_feed:match',
    'unit_sales:view',
    'unit_sales:edit',
    'investor:view_waterfall',
    'investor:download_report',
    'ai_analyst:query',
  ],
  FINANCE: [
    'portfolio:view',
    'project:view_overview',
    'project:view_financials',
    'acquisition:view',
    'financing:view',
    'financing:edit',
    'budget:view',
    'budget:edit',
    'change_order:create',
    'change_order:approve',
    'contingency:view',
    'contingency:manage',
    'draw:view',
    'draw:create_packet',
    'draw:review_queue',
    'draw:approve_lines',
    'milestone:view',
    'recon:view',
    'recon:edit',
    'accounting:recon_matrix',
    'waiver:audit_view',
    'waiver:audit_manage',
    'document:view',
    'document:upload',
    'amex_feed:match',
    'unit_sales:view',
    'investor:view_waterfall',
    'investor:download_report',
    'ai_analyst:query',
  ],
  PROJECT_MANAGER: [
    'project:view_overview',
    'acquisition:view',
    'permits:view',
    'permits:edit',
    'budget:view',
    'milestone:view',
    'milestone:log_progress',
    'delay:attribute',
    'field_log:create',
    'document:view',
    'document:upload',
    'ai_analyst:query',
  ],
  ACCOUNTANT: [
    'project:view_overview',
    'budget:view',
    'draw:view',
    'recon:view',
    'recon:edit',
    'accounting:recon_matrix',
    'waiver:audit_view',
    'waiver:audit_manage',
    'document:view',
    'document:upload',
    'amex_feed:match',
    'ai_analyst:query',
  ],
  INVESTOR: [
    'project:view_overview',
    'unit_sales:view',
    'investor:view_waterfall',
    'investor:download_report',
    'document:view',
    'ai_analyst:query',
  ],
  VIEWER: [
    'project:view_overview',
    'permits:view',
    'milestone:view',
    'document:view',
    'ai_analyst:query',
  ],
};

const fullPermissions: Record<string, Permission[]> = {
  ...basePermissions,
  GENERAL_CONTRACTOR: [
    'project:view_overview',
    'milestone:view',
    'milestone_claim:submit',
    'field_log:create',
    'change_order:create',
    'document:view',
    'document:upload',
    'ai_analyst:query',
  ],
  DEVELOPER_OWNER: basePermissions.OWNER,
  CFO: basePermissions.FINANCE,
  PM: basePermissions.PROJECT_MANAGER,
  GC_FIXED: [
    'milestone:view',
    'milestone_claim:submit',
    'change_order:create',
    'ai_analyst:query',
  ],
  GC_DAILY: [
    'milestone:view',
    'field_log:create',
    'ai_analyst:query',
  ],
};

export const ROLE_PERMISSIONS: Record<string, Permission[]> = fullPermissions;
