import { UserRole } from '../types';
import { Permission } from './permissions';

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  DEVELOPER_OWNER: [
    'portfolio:view',
    'project:create',
    'project:delete',
    'project:view_overview',
    'project:view_financials',
    'project:settings',
    'deal_lab:access',
    'deal_lab:save_project',
    'budget:view',
    'budget:edit',
    'change_order:create',
    'change_order:approve',
    'contingency:view',
    'contingency:manage',
    'draw:view',
    'draw:create_packet',
    'draw:review_queue',
    'draw:approve_lines',
    'draw:disburse_wire',
    'milestone:view',
    'milestone:log_progress',
    'delay:attribute',
    'field_log:create',
    'milestone_claim:submit',
    'accounting:recon_matrix',
    'waiver:audit_view',
    'waiver:audit_manage',
    'document:view',
    'document:upload',
    'amex_feed:match',
    'unit_sales:view',
    'unit_sales:edit',
    'investor:view_waterfall',
    'investor:download_report',
    'ai_analyst:query',
  ],
  CFO: [
    'portfolio:view',
    'project:view_overview',
    'project:view_financials',
    'budget:view',
    'budget:edit',
    'change_order:create',
    'change_order:approve',
    'contingency:view',
    'contingency:manage',
    'draw:view',
    'draw:create_packet',
    'milestone:view',
    'accounting:recon_matrix',
    'waiver:audit_view',
    'waiver:audit_manage',
    'document:view',
    'document:upload',
    'amex_feed:match',
    'unit_sales:view',
    'investor:view_waterfall',
    'investor:download_report',
    'ai_analyst:query',
  ],
  PM: [
    'project:view_overview',
    'budget:view',
    'milestone:view',
    'milestone:log_progress',
    'delay:attribute',
    'document:view',
    'ai_analyst:query',
  ],
  LENDER: [
    'draw:review_queue',
    'draw:approve_lines',
    'draw:disburse_wire',
    'document:view',
    'waiver:audit_view',
    'ai_analyst:query',
  ],
  GC_FIXED: [
    'milestone:view',
    'milestone_claim:submit',
    'change_order:create',
    'ai_analyst:query',
  ],
  GC_DAILY: [
    'milestone:view',
    'field_log:create',
    'ai_analyst:query',
  ],
  INVESTOR: [
    'unit_sales:view',
    'investor:view_waterfall',
    'investor:download_report',
    'ai_analyst:query',
  ],
  ACCOUNTANT: [
    'budget:view',
    'draw:view',
    'accounting:recon_matrix',
    'waiver:audit_view',
    'waiver:audit_manage',
    'document:view',
    'amex_feed:match',
    'ai_analyst:query',
  ],
};
