import { AlertItem, ChangeOrderItem } from './types';
import { ContingencyMovement, UnitSale, AmexCardTransaction } from '../../../shared/types';
export * from './initial-budget-data';

export const getInitialContingencyMovements = (projectId: string): ContingencyMovement[] => [
  {
    id: 'cm-1',
    project_id: projectId,
    source_category: 'Contingency Reserve',
    destination_category: 'Foundation',
    amount: 40000,
    reason: 'Unexpected soft soil encountered requiring extra piles to bear building load.',
    status: 'APPROVED',
    approved_by: 'Hardik Parikh (Owner)',
    approved_at: 'Mar 18, 2026',
  },
];

export const getInitialChangeOrders = (projectId: string): ChangeOrderItem[] => {
  try {
    const stored = localStorage.getItem(`groundup_change_orders_${projectId}`);
    if (stored) return JSON.parse(stored);
  } catch {}
  return [
    {
      id: 'co-1',
      number: 'CO-001',
      category: 'Foundation',
      sub_section: 'Substructure & Pile Reinforcement',
      cost_code: '03-100',
      amount: 40000,
      reason: 'Unforeseen soft soil condition',
      description: 'Engineered grade beams and extra helical piles required by structural engineer.',
      status: 'APPROVED',
      visible_to_gc: true,
      gc_notes: 'Owner approved. GC authorized to proceed with foundation underpinning.',
      date: 'Mar 18, 2026',
      is_other: false,
    },
    {
      id: 'co-other-1',
      number: 'CO-002',
      category: 'Municipal Utility Easement Relocation',
      sub_section: 'Off-Site Civil & Utility Trenching',
      cost_code: '02-310',
      amount: 18500,
      reason: 'Township Utility Conflict',
      description: 'PSE&G mandated emergency lateral line relocation across west boundary easement.',
      status: 'APPROVED',
      visible_to_gc: true,
      gc_notes: 'Approved lateral rework. GC coordinated with municipal inspectors.',
      date: 'Apr 02, 2026',
      is_other: true,
    },
  ];
};

export const getInitialUnitSales = (projectId: string): UnitSale[] => [
  {
    id: 'u-1',
    project_id: projectId,
    unit_name: 'Unit 1 — Penthouse Duplex (4th Fl)',
    sq_ft: 1800,
    beds_baths: '3 Bed / 2.5 Bath · Private Roof Deck',
    asking_price: 1250000,
    contract_price: 1225000,
    deposit_amount: 122500,
    status: 'UNDER_CONTRACT',
    buyer_name: 'Dr. Robert Chen (Attorney Review Complete)',
    contract_date: 'Aug 14, 2026',
    closing_date: 'Nov 30, 2026',
    broker_commission_pct: 0.03,
    closing_costs_est: 18000,
    net_proceeds: 1170250,
    loan_payoff_allocation: 650000,
    investor_distribution: 520250,
  },
  {
    id: 'u-2',
    project_id: projectId,
    unit_name: 'Unit 2 — Mid-Floor Residence (3rd Fl)',
    sq_ft: 1600,
    beds_baths: '2 Bed / 2 Bath · Balcony',
    asking_price: 1050000,
    contract_price: undefined,
    deposit_amount: undefined,
    status: 'AVAILABLE',
    buyer_name: undefined,
    broker_commission_pct: 0.03,
    closing_costs_est: 15000,
    net_proceeds: 1003500,
    loan_payoff_allocation: 444000,
    investor_distribution: 559500,
  },
  {
    id: 'u-3',
    project_id: projectId,
    unit_name: 'Unit 3 — Garden Duplex (1st & 2nd Fl)',
    sq_ft: 1400,
    beds_baths: '2 Bed / 2 Bath · Private Yard',
    asking_price: 980000,
    contract_price: 980000,
    deposit_amount: 98000,
    status: 'UNDER_CONTRACT',
    buyer_name: 'Amanda & Liam Vance',
    contract_date: 'Sep 2, 2026',
    closing_date: 'Dec 15, 2026',
    broker_commission_pct: 0.03,
    closing_costs_est: 14000,
    net_proceeds: 936600,
    loan_payoff_allocation: 0,
    investor_distribution: 936600,
  },
];

export const getInitialAmexTransactions = (projectId: string): AmexCardTransaction[] => [
  {
    id: 'tx-1',
    project_id: projectId,
    card_last4: '8421',
    card_label: 'Amex Project Card · 73 Broadway',
    date: 'Oct 3, 2026',
    vendor: 'Home Depot #4812',
    amount: 3482,
    ai_suggested_category: 'Flooring & Finishes',
    ai_confidence: 82,
    status: 'NEEDS_REVIEW',
    memo: 'Finish trim nails and subfloor adhesive',
    evidence_strength: 'CARD_TRANSACTION',
  },
  {
    id: 'tx-2',
    project_id: projectId,
    card_last4: '8421',
    card_label: 'Amex Project Card · 73 Broadway',
    date: 'Sep 29, 2026',
    vendor: 'Sylvia Concrete LLC',
    amount: 14200,
    ai_suggested_category: 'Foundation',
    ai_confidence: 98,
    status: 'MATCHED',
    memo: 'Foundation cure batch #4',
    evidence_strength: 'BANK_TRANSACTION',
  },
  {
    id: 'tx-3',
    project_id: projectId,
    card_last4: '8421',
    card_label: 'Amex Project Card · 73 Broadway',
    date: 'Sep 24, 2026',
    vendor: 'Kuiken Brothers Lumber',
    amount: 8750,
    ai_suggested_category: 'Framing',
    ai_confidence: 96,
    status: 'MATCHED',
    memo: 'Roof rafters and 2x10 joists',
    evidence_strength: 'VERIFIED_INVOICE',
  },
];

export const INITIAL_ALERTS: AlertItem[] = [
  {
    id: 'a1', severity: 'critical', type: 'RECONCILIATION_EXCEPTION',
    title: 'Plumbing spend ahead of verified progress',
    description: '82% of plumbing budget has been spent but only 55% is verified as complete. This delta exceeds the 15% threshold.',
    details: { spent: '$55,760', budget: '$68,000', progress: '55%', delta: '+27%' },
    action: 'View Budget Tab',
    createdAt: 'Oct 4, 2026',
    resolved: false,
  },
  {
    id: 'a2', severity: 'high', type: 'SCHEDULE_DELAY',
    title: 'Cumulative schedule delay: 82 days',
    description: 'Project milestones have accumulated 82 days of delay since groundbreaking. Estimated additional carrying cost: $26,568.',
    details: { delayDays: '82 days', dailyCost: '$324/day', totalImpact: '$26,568' },
    action: 'View Timeline',
    createdAt: 'Oct 5, 2026',
    resolved: false,
  },
  {
    id: 'a3', severity: 'medium', type: 'OVER_BUDGET',
    title: 'Site Work over budget by $4,000',
    description: 'Site Work category has spent $82,000 against an approved budget of $78,000. Absorb from 10% Reserve Contingency.',
    details: { budget: '$78,000', spent: '$82,000', variance: '+$4,000' },
    action: 'Absorb Overrun',
    createdAt: 'Oct 2, 2026',
    resolved: false,
  },
];
